CREATE TABLE Test(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY ,
  name VARCHAR (20),
  title VARCHAR (50)
);

INSERT INTO Test(id,name,title) VALUES (1,'张三','总裁兼CEO');
INSERT INTO Test(id,name,title) VALUES (2,'李四','部门负责人');
